
execute 'source ~/.config/nvim/keysmapping.vim'
execute 'source ~/.config/nvim/plugin.vim'
execute 'source ~/.config/nvim/nerdtree.vim'
execute 'source ~/.config/nvim/markdown.vim'
" execute 'source ~/.config/nvim/defx.vim'
execute 'source ~/.config/nvim/fzf.vim'
execute 'source ~/.config/nvim/airline.vim'
execute 'source ~/.config/nvim/coc.vim'
execute 'source ~/.config/nvim/filetype.vim'
execute 'source ~/.config/nvim/floaterm.vim'
